version: 2
registries:
  aap-domain :
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/aap-domain
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}
 boot-cluster-conditionals :
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/boot-cluster-conditionals
    username: x-access-token
    password: ${{ secrets.READER_TOKEN }}   
updates:
- package-ecosystem: github-actions
    directory: "/"
    schedule:
      time: "12:40"
      interval: daily
    open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/"
  registries:
      - aap-domain
      - boot-cluster-conditionals
  schedule:
    interval: daily
    time: "12:40"
  open-pull-requests-limit: 10
