version: 2
registries:
  aap-domain :
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/aap-domain
    username: x-access-token
    password: ${{ secrets.GITHUB_TOKEN }}
updates:
- package-ecosystem: github-actions
    directory: "/"
    schedule:
      time: "11:00"
      interval: daily
    open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/"
  registries:
      - aap-domain
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
